name = "techxpress"
main = ".open-next/worker.js"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "techxpressdz.com", custom_domain = true },
  { pattern = "www.techxpressdz.com", custom_domain = true }
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
html_handling = "auto-trailing-slash"
not_found_handling = "single-page-application"
